Initial commit for #313 - Create expandable list component
polubis/Dream-stack-for-React-dev pull request #349
Opened 2023-11-10 10:36 UTC by JakubWierzchowski

I created a folder named "expandable-list" in system/apps/blog/components. I wasn't sure where to place this section because the page /courses/react-hooks-spellbook/ hasn't been created yet. I also haven't added a link to these articles. The component itself should function correctly.

2023-11-15 17:26 UTC, polubis requested changes

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +  const [openStates, setOpenStates] = useState(data.map(() => true));
This is causing data.map on every rerender

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +import data from './data.json';
Only bounded to single data type.

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.style.ts
> +export const Wrapper = styled.div`
You're not reusing any of currently implemented code

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/data.json
> +  {
It will cause a need of double mapping, if model taken from BE for example will be different, firstly you need to map to model, and then inside the component you will map again to render the markup

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/data.json
> +    "button": ">",
No option to customize any stuff, positioning, content inside or triggers

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +import { SubList, Wrapper } from './expandable-list.style';
You should follow current conventions in code base, if you have suggestion/or tips, please prepare a PoC with it, and we'll vote about these ideas

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +    const updatedOpenStates = [...openStates];
This will produce a bug, you should rely on previous state with 

```ts
setSomething(prevState => // return result here
```

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +        {data.map((item, index) => (
Index as a key is easy way to get bugs...

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +                    transform: openStates[index]
You may use simple classes to get rid of style object creation foe each node

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +      <span>Chapters & lessons</span>
The heading should be not a part of this component

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +            <li onClick={() => handleClick(index)}>
You may avoid creating a function on every render with data-attributes passed to event callback

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +                    xmlns="http://www.w3.org/2000/svg"
No option to provide custom expander

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +                style={{ display: openStates[index] ? 'flex' : 'none' }}
Do not use a styles to hide stuff for this case, it should be just unmounted with if statement

2023-11-15 17:26 UTC, polubis commented on system/apps/blog/views/home/home.view.tsx
> +import ExpandableList from 'apps/blog/components/expandable-list/expandable-list';
This line should be removed

2023-11-15 17:26 UTC, polubis commented
@JakubWierzchowski  I'll add all needed changes, and when finished, I will notify you, that's ok?

2023-11-16 07:26 UTC, merged

2023-11-16 10:33 UTC, JakubWierzchowski commented
> I'll add all needed changes, and when finished, I will notify you, that's ok?

Yes. Thank you for all your tips. I hoped this was a more correct solution :)

2023-11-16 10:45 UTC, JakubWierzchowski commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +import data from './data.json';
Is it advisable to create a main component from which I can pass data like below?
import data from './data1.json';
import data2 from './data2.json';

    <ExpandableList data={data} />
    <ExpandableList data={data2} />

2023-11-16 10:49 UTC, JakubWierzchowski commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +  const [openStates, setOpenStates] = useState(data.map(() => true));
Should i use useMemo?

 const memoizedList = useMemo(() => data.map(() => true), [data]);
  const [openStates, setOpenStates] = useState(memoizedList);

2023-11-16 10:55 UTC, JakubWierzchowski commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +                style={{ display: openStates[index] ? 'flex' : 'none' }}
Should there be such a solution?
{openStates[index] && (
  <SubList key={subIndex}>
    {/* Sublist content */}
  </SubList>
)}

2023-11-16 12:24 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +import data from './data.json';
Only in application logic, not inside library itself.

2023-11-16 12:24 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +                style={{ display: openStates[index] ? 'flex' : 'none' }}
Yes

2023-11-16 12:24 UTC, polubis commented
> > I'll add all needed changes, and when finished, I will notify you, that's ok?
> 
> Yes. Thank you for all your tips. I hoped this was a more correct solution :)

No worries, great work

2023-11-16 12:25 UTC, polubis commented on system/apps/blog/components/expandable-list/expandable-list.tsx
> +  const [openStates, setOpenStates] = useState(data.map(() => true));
It's much better to use initializer in useState -> useState(your_complex_function_to_calculate)