Feature blackquote
polubis/Dream-stack-for-React-dev pull request #40
Opened 2023-06-06 09:22 UTC by FrontendKedra

2023-06-14 07:44 UTC, polubis requested changes
There is one re-export missing in main lib directory, despite that great work - you can improve it or just leave it to me u2y

2023-06-14 07:44 UTC, polubis commented on system/libs/figa-ui/src/lib/blackquote/blackquote.stories.tsx
In every place where you importing type you need to add type alias - import type... 


It speeds up TS builds.

2023-06-14 07:44 UTC, polubis commented on system/libs/figa-ui/src/lib/blackquote/blackquote.test.tsx
Look how other component tests are described.


It should be 

There is option to use blackquote when:

2023-06-14 07:44 UTC, polubis commented on system/libs/figa-ui/src/lib/blackquote/blackquote.tsx
Import type

2023-06-14 08:33 UTC, FrontendKedra commented on system/libs/figa-ui/src/lib/blackquote/blackquote.stories.tsx
Thank you for valuable information, I've implemented the fixes to imports

2023-06-15 06:53 UTC, polubis commented
@FrontendKedra closing your PR and merging via this one ->
https://github.com/polubis/Dream-stack-for-React-dev/pull/102/files

Which have small improvements. Please check in free time.

2023-06-15 06:53 UTC, closed without merging